#!/bin/bash
# fq - force quit a process

# kill wrapper that pipes output to /dev/null and uses sudo when necessary
# returns 0 if process is killed, 1 if process still running
kill() {
  command kill "$@" >/dev/null 2>&1
  if [ $? -eq 1 ]
  then
    sudo kill "$@" >/dev/null 2>&1
  fi
  ! ps "${@: -1}" >/dev/null 2>&1
}

pid=$(ps -ax | fzf | cut -d\  -f1)
if [ ! -z "$pid" ]
then
  if ! kill "$pid" # SIGTERM
  then
    sleep 0.1 # give the process a moment to clean up
    kill -9 "$pid" # SIGKILL
  fi
fi
